### PR TITLE
Update embedded Android SDK to 24.4.1

### PR DESCRIPTION
**Pull request by mpiggott**
I mentioned this on list a couple weeks ago but I took a stab at updating Andmore to the latest Android SDK.  Its probably been ~5-years since I've worked on an Android project so likely worth someone verifying behaviour.  Most of the changes were around the removal of `LanguageQualifier` and `RegionQualifier` in favour of `LocaleQualifier`

Its possible some of what I fixed here is unrelated to the SDK update, for me at least the develop (master) branch already had quite a few test failures.

Some notes:
* `ScreenRoundQualifier` - will need an icon in ResourceHelper (or the test relaxed to ignore it)
* Its possible *org.eclipse.andmore.base* may require *builder-model.jar* and *commons-compress-1.8.1.jar*, one of the manifests declared them as dependencies but unlike *annotations.jar* and *gson-2.2.4.jar* there was no obvious breakage

### CODE REVIEW

**Comment by kingargyle** [comment]
Hey thanks for the pull request, can you please sing the eclipse CLA so we can review and merge the request.  Also the commits will need to be updated to follow the CLA guidelines.

**Comment by kingargyle** [comment]
Since this uses the newer JAR files and dependencies, we'll need to run this through eclipse IP process.  So this particular change may take a while to get into place.

@dschaefer @kaloyan-raev Tagging you guys on this as well.

**Comment by mpiggott** [comment]
@kingargyle sorry for the delay I was distracted and finally got around to looking back at the CLA email. I used bug 461942 as this is a superset of that change, I can file a new one if you prefer.

**Comment by kingargyle** [comment]
No problem.  Because this updates the embedded jars, we'll have to run these through the eclipse IP process to get them approved.  The good thing is that since we already have the originals approved it shouldn't take as long as the first time I went through this.

A couple of questions do you have links to the sources for these versions of the jars, and the source where you got the binaries from?  I'll need those when I submit the jars for approval.

**Comment by mpiggott** [comment]
I originally used the SDK tools to download them, I've now double checked that the Windows download from https://developer.android.com/sdk/index.html#Other ( http://dl.google.com/android/android-sdk_r24.4.1-windows.zip ) does match the files downloaded.

Inside the zip all the jars can be found in:
* android-sdk-windows/tools/lib/

I believe the source lives - https://android.googlesource.com/platform/tools/base/

Its not clear to me what rev matches 24.4.1

**Comment by mpiggott** [comment]
Looks like gson 2.2.4 is already in Orbit so we could consume that instead.  Guava unfortunately is @ 15

**Comment by kingargyle** [comment]
@mpiggott yeah, Ideally I'd like to get away from embedding the jars and just get them for orbit.

**Comment by kingargyle** [comment]
@mpiggott just checking to see if you are interested in possibly becoming a committer to the project?  We can use all the help we can get and you've done some good work with the couple of pull requests you have submitted.

It'll also help get this particular pull request moved along at a faster rate.

**Comment by mpiggott** [comment]
@kingargyle sure, I'm not sure about long term but I can certainly help to get Andmore ready w/ Neon.

**Comment by kingargyle** [comment]
No full time commitment is necessary.  Can you join the Android-Dev mailing list, and just post a message I believe @kaloyan-raev is currently starting the process to get this moved through eclipse IP.

Once you've joined the android-dev mailing list, I'll get the nomination process started.

**Comment by mpiggott** [comment]
@kaloyan-raev I'm already on the list w/ my alternate email, do I need to join with the CLA email instead?

**Comment by kingargyle** [comment]
Nope.  I just need to know your eclipse committer id, please email me at kingargyle at gmail dot com and I can get the election review started.

**Comment by kingargyle** [comment]
@mpiggott I submitted your nomination to the andmore project.  It'll take at most 7 days until the nomination process is complete.

**Comment by kingargyle** [comment]
@mpiggott nomination has been completed.  Let me know if you don't have commit rights to the repository.

**Comment by kaloyan-raev** [comment]
We have a "check in" permission by the IP team.

**Pull request merged**
