### PR TITLE
[471901] Android Common XML Editor should not be the default

### PR DESCRIPTION
**Pull request by kaloyan-raev**
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=471901
Signed-off-by: Kaloyan Raev <kaloyan.r@zend.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471901

**Comment by rgladwell** [comment]
:+1: This has been bugging me for years.

**Comment by kingargyle** [comment]
Thanks @kaloyan-raev I'll run a pull request for this and merge once it completes.

**Comment by kingargyle** [comment]
This looks good, unfortunately for some reason I don't have write access to the github repo here at the momement so I'll get this merged once that is straightened out.

**Comment by kaloyan-raev** [comment]
@kingargyle No worries :-)

**Pull request merged**
