### PR TITLE
[476446] MultiDex support for Android APK

### PR DESCRIPTION
**Pull request by NuclearFlox**
Signed-off-by: Thys ten Veldhuis <t.tenveldhuis@gmail.com>

Added basic support for multi-dex. You can enable it by going to 

*Project > Properties > Android > General* and enabling the 'Enable MultiDex support' checkbox. This then adds two properties to the project.properties file:

> multidex.enabled=true
> multidex.main-dex-list=main-dex-list.txt

Enabling the checkbox also copies the *main-dex-list.txt* file so the user can specify which classes to include in the classes.dex which is automatically loaded before `MultiDex.install` is executed.

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=476446

**Comment by kingargyle** [comment]
Running the pull request verification now against the project., will try and take a deeper look after lunch.

https://hudson.eclipse.org/andmore/job/Andmore-Develop-PullRequests/

**Comment by kingargyle** [comment]
This looks pretty good.  Can you take a bit of time and add a few Intergration/Unit Tests for the new functionality?  You can base the work off the existing unit tests.  This will give us some sanity checks that functionality is still working as we make additional changes.

**Comment by NuclearFlox** [comment]
Sure I can. Should I add the Intergration/Unit Tests in a new commit and create a additional pull request or should  we close this pull request, squash everything in to a single commit and create a new request?

**Comment by kingargyle** [comment]
You can have it in a new commit and go ahead and add it this existing pull request.  If we really want we can resquash this commit and just force push the new commit to your branch.  No need for a new pull request.

**Comment by kingargyle** [comment]
As for testing, Ideally class level/method level testing, but also the new UI functionality and making sure it creates the necessary output files you expect.  Just something that covers the basics and make sure things work.

**Comment by NuclearFlox** [comment]
Oke, hope to finish it by the end of the week.

**Comment by NuclearFlox** [comment]
I have added some tests to ensure core functionality.

**Comment by kingargyle** [comment]
Thanks.  I'll get this run today.

**Comment by kingargyle** [comment]
Ran the pull request against our Hudson instance, there are three tests that failed for the Dexing.  You can view them here:

https://hudson.eclipse.org/andmore/job/Andmore-Develop-PullRequests/lastCompletedBuild/testReport/

**Comment by NuclearFlox** [comment]
I will look in to it as soon as possible.

**Comment by NuclearFlox** [comment]
I have made an incorrect assumption in the tests, I have found the issue and will resolve this.

**Comment by NuclearFlox** [comment]
I have added a modification and several checks for ensuring correct BuildToolInfo. The test now appears to be working properly.

**Comment by NuclearFlox** [comment]
I saw the last check also failed on the dexOutputFutures field, I will make an additional change to ensure this test will pass as well.

**Comment by kingargyle** [comment]
Thanks, I re-ran it last night and we had one Dex test failure.  I'm re-running again to see if it is just a random failure or not, but it looked much better.

https://hudson.eclipse.org/andmore/job/Andmore-Develop-PullRequests/137/testReport/org.eclipse.andmore.internal.build/DexWrapperTest/testMainClassFieldsAvailable/

**Comment by kingargyle** [comment]
Looks like all your tests now pass.  I'm going to go ahead and merge this into develop.  Thanks for the contribution!

**Comment by rolandhediger** [comment]
This is a great feature, however somehow it seems in my particular case that the adjustments I make to the main-dex-list.txt do not seem to be working in the build, i.e my main application class is not in classes.dex. Is there a way to set the dx process to verbose so I could find some helpful error messages? Thanks.

**Pull request merged**
