### PR TITLE
MultiDex

### PR DESCRIPTION
**Pull request by NuclearFlox**
Added basic support for multi-dex. You can enable it by going to 

*Project > Properties > Android > General* and enabling the 'Enable MultiDex support' checkbox. This then adds two properties to the project.properties file:

> multidex.enabled=true
> multidex.main-dex-list=main-dex-list.txt

Enabling the checkbox also copies the *main-dex-list.txt* file so the user can specify which classes to include in the classes.dex which is automatically loaded before `MultiDex.install` is executed.

### CODE REVIEW

**Comment by NuclearFlox** [comment]
As I understand the CLA check failed. I requested the CLA just before creating the pull request.

**Comment by kingargyle** [comment]
Thanks for this.   A couple of things.

Can you squash the items down into one commit.  It'll just make it easier to back out if it is necessary.

Also, please in the comment for the new commit, include the bug number, and Sign off items.  Once your CLA has been approved you can resubmit the pull request.

Thanks again for taking the time to contribute the changes.

I created a new bug for this for tracking purposes.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=476446

**Comment by NuclearFlox** [comment]
Oke I will squash everything in to a single commit and Sign off on it. Do you know if I get a notification when the CLA has been approved?

**Comment by kingargyle** [comment]
You can go to https://projects.eclipse.org/ and log in, then click the CLA link, and it will show you the status.

**Comment by NuclearFlox** [comment]
It says "The CLA we have on record for you will expire on 2018-09-02". I have squashed everything in to a single commit with the bug information. Should I create a new pull request?

**Pull request closed without merging**
