### PR TITLE
[Bug 526437] - Android SWT Libraries need to be forked

### PR DESCRIPTION
**Pull request by Kys3rK1ng**
Forked AOSP SWT according to "How to fork Android on GitHub"
(https://www.bitleaks.net/blog/fork-android-on-github/).
This project was revised to build the dependencies required by Andmore
as bundles using Maven/Tycho. The relevant parts were then merged to
Andmore as a new trunk named "andmore-swt". The enlarged Andmore project
has built to completion with Maven, but with integration test errors.
Regardless, the pull request is proceeding, as the android-swt part of
the build is successful.

Note the orginal Andmore target has been updated and incorporated in the
Tycho target platform configuration so both Maven and Eclipse can share
the same target. 

Also note that the original Android base module has been replaced by the
new SWT org.eclipse.andmore.swt module.
    
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=526437
Signed-off-by: Andrew Bowley <andrewbowley@aapt.net.au>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=526437

**Comment by andrew-bowley** [comment]
Performed forced push to amend "signed off by".

>git push --force origin develop
...
remote: Resolving deltas: 100% (231/231), completed with 4 local objects.
To https://github.com/Kys3rK1ng/andmore.git
 + d2d5f86...b650b80 develop -> develop (forced update)

**Comment by kingargyle** [comment]
I've submitted the CQ for eclipse IP to start the review of the source code for this contribution.

**Comment by kingargyle** [comment]
@Kys3rK1ng I tried running this pull request, and we are getting a issue, when trying to resolve the POM files for the new bundles.  See the following for the issue.  Also, there are currently 15 known test failures that are happening, it varies from time to time, but just something to keep in mind, if you see more than 15 then we have problems.

https://hudson.eclipse.org/andmore/job/Andmore-Develop-PullRequests/170/console

**Comment by Kys3rK1ng** [comment]
I have pushed an update to resolve the build issue. I assume I did not observe the issue because I omitted to clear the Andmore plugins cached in my local repository. To avoid such traps in the future, I am keen to set up an Andmore build on my own Jenkins CI installation. As you are using Hudson, it makes me think this is possible. Any clues running the Eclipse workbench from a CI server job would be appreciated.

**Comment by kingargyle** [comment]
@Kys3rK1ng what system are you using to develop on?   If you want to run the tests you will need a way to create a virtual display for the CI system, so it can run the UI tests.   Typically on Linux boxes this is done with VNC or XVNC plugins for Jenkins.

https://wiki.jenkins.io/display/JENKINS/VncViewer+Plugin

**Comment by kingargyle** [comment]
Alright this build looks right.   We got the same general 15 failures that we have been getting for a while.

https://hudson.eclipse.org/andmore/job/Andmore-Develop-PullRequests/171/

Let me know if you want me to merge this, so that it doesn't block any of the other work you have in the pipeline.  This is going through Parallel IP review so we have permision to merge the code into the git repository.

**Comment by Kys3rK1ng** [comment]
I am not currently blocked waiting for the merge as I am using a stand alone application to develop the new sdkuilib module. If the opportunity presents itself, I would prefer to merge only after swapping the old sdkuilib module with the new one .

**Comment by kingargyle** [comment]
We can hold it until you are ready for it to be merged.

**Comment by Kys3rK1ng** [comment]
As stated in https://bugs.eclipse.org/bugs/show_bug.cgi?id=526437, I am happy for the pull request to proceed. I have included a complete list of dependencies to allow a check for outstanding license issues.

Unfortunately there has been a merge yesterday into xhteam/tools-motodev by Raymond Wang. This happened without warning and before the final commit. I will try to contact Raymond and get rectification under way.

**Comment by kingargyle** [comment]
Don't worry about the xhteam.  We aren't posting things to that repository, this is the official repo for Andmore.

**Comment by kingargyle** [comment]
This has been merged.

**Pull request merged**
