### PR TITLE
SDK Management needs update

### PR DESCRIPTION
**Pull request by andrew-bowley**
Andmore SDK Management covers package install and updates and virtual device configuration. The design appears to be unchanged from Android API 8. The pull request for Bug 526437 - Android SWT Libraries need to be forked - has been merged, and this contains features that can improve the user experience regarding SDK Management. Attached is a PDF which proposes the changes to be made.
[sdk-api27.pdf](https://github.com/eclipse/andmore/files/1526020/sdk-api27.pdf)

### CODE REVIEW

**Comment by cybersearch2** [comment]
This is a failed experiment and I cannot find the "undo" button. Please close the request and then I can delete it.

**Comment by kingargyle** [comment]
@andrew-bowley do you want me to close this PR?

**Comment by andrew-bowley** [comment]
Dave
Please close this PR. I can then delete it, which is what I really want to do. 

Andrew

**Comment by kingargyle** [comment]
Closing per request.

**Pull request closed without merging**
